version: "3"

tasks:
  # Development Tools
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --cmd="go run ./cmd/server/main.go" --proxy="http://localhost:42069" --open-browser=false

  tailwind-build:
    desc: Build tailwind output (prod-ish)
    cmds:
      - ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --minify

  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --clean

  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --watch

  fe-install:
    cmds:
      - cd frontend && bun install

  fe-build:
    cmds:
      - cd frontend && bun run build

  fe-watch:
    cmds:
      - cd frontend && bun run dev:board
  # Start development server
  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-build
    cmds:
      - echo "Starting app..."
      - sleep 2
      - task --parallel tailwind-watch templ fe-watch
