version: "3"

tasks:
  # Development Tools
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --cmd="go run ./cmd/server/main.go" --proxy="http://localhost:42069" --open-browser=false

  tailwind-build:
    desc: Build tailwind output (prod-ish)
    cmds:
      - ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --minify

  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --clean

  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - ./tailwindcss -i ./static/css/input.css -o ./static/css/output.css --watch

  ts-install:
    desc: Install deps for static/js build 
    dir: ./frontend
    cmds:
      - bun install

  bun-install:
    desc: Install bun deps for frontend workspace (core + web)
    dir: ./frontend
    cmds:
      - bun install

  web-build:
    desc: Build web package once (writes to ./static/js)
    deps: [bun-install]
    dir: ./frontend/packages/web
    cmds:
      - bun run build

  web-watch:
    desc: Watch build web package to ./static/js (NOT a dev server)
    deps: [bun-install]
    dir: ./frontend/packages/web
    cmds:
      - bun run watch

  dev:
    desc: Start dev loop (templ + tailwind + web watch)
    deps:
      - tailwind-build
      - bun-install
      - web-build
    cmds:
      - task --parallel tailwind-watch templ web-watch

  backup:
    desc: Create a data backup archive
    cmds:
      - ./scripts/backup.sh data

  restore:
    desc: Restore data from backup archive
    cmds:
      - ./scripts/restore.sh {{.ARCHIVE}}

  backup-drill:
    desc: Run backup/restore drill and verify digest parity
    cmds:
      - ./scripts/backup_drill.sh data /tmp

  uat-smoke:
    desc: Run API-level UAT smoke suites for server/board/task systems
    cmds:
      - ./scripts/uat_smoke.sh

  coverage-gate:
    desc: Run Go coverage gate (default threshold 90)
    cmds:
      - ./scripts/coverage_gate.sh {{.THRESHOLD | default "90"}}

  qa-gate:
    desc: Run full QA gate (UAT smoke + Go coverage + frontend build)
    cmds:
      - ./scripts/qa_gate.sh {{.THRESHOLD | default "90"}}
