// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// TodaysGoalsSidebarContent contains the inner content, reused by desktop and mobile wrappers
func TodaysGoalsSidebarContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Header --><div class=\"sticky top-0 border-b border-border bg-zinc-900 px-4 py-3\"><div class=\"flex items-center gap-2\"><span class=\"text-red-500\">⚔️</span> <span class=\"text-sm font-bold tracking-wide text-white\">TODAY'S GOALS</span></div></div><!-- Task Summary --><div class=\"border-b border-border px-4 py-3\"><div class=\"mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500\">Task Summary</div><div class=\"mb-2 flex items-center gap-2\"><span class=\"text-xs text-zinc-400\">Danger:</span> <span data-goal=\"danger-badge\" class=\"rounded bg-green-500/20 px-2 py-0.5 text-xs font-medium text-green-400\">SAFE</span></div><div class=\"space-y-1 text-xs text-zinc-400\"><div>Villagers: <span data-goal=\"villager-count\" class=\"text-zinc-200\">0 live / 0 total</span></div><div>Tasks: <span data-goal=\"task-count\" class=\"text-zinc-200\">0 active + 0 completed today</span></div></div></div><!-- Villager Stamina --><div class=\"border-b border-border px-4 py-3\"><div class=\"mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500\">Villager Stamina</div><div data-goal=\"villager-stamina-list\" class=\"space-y-1 text-xs text-zinc-400\"><div class=\"text-zinc-500\">No villagers deployed</div></div></div><!-- Active Tasks --><div class=\"border-b border-border px-4 py-3\"><div class=\"mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500\">Active Tasks</div><div data-goal=\"active-tasks-list\" class=\"space-y-1 text-xs text-zinc-400\"><div class=\"text-zinc-500\">No tasks completed today</div></div></div><!-- Success Checklist --><div class=\"px-4 py-3\"><div class=\"mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500\">Success Checklist</div><div data-goal=\"success-checklist\" class=\"space-y-2 text-xs\"><div class=\"text-zinc-500\">Goals will update as you play.</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// TodaysGoalsSidebar wraps the content for desktop view
func TodaysGoalsSidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"h-full w-full border-r border-border bg-zinc-900/95 backdrop-blur overflow-y-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TodaysGoalsSidebarContent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
