// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex h-full w-full items-center justify-center bg-background px-4\"><div class=\"w-full max-w-md rounded-xl border border-border bg-card p-5 shadow-sm\"><div class=\"mb-4\"><h1 class=\"text-lg font-semibold\">Sign In</h1><p class=\"mt-1 text-sm text-muted-foreground\">Use email OTP to access your Donegeon board.</p></div><form id=\"emailStep\" class=\"space-y-3\"><label class=\"block text-sm font-medium\" for=\"emailInput\">Email</label> <input id=\"emailInput\" type=\"email\" required autocomplete=\"email\" placeholder=\"you@example.com\" class=\"w-full rounded-md border border-input bg-background px-3 py-2 text-sm\"> <button id=\"emailSubmit\" type=\"submit\" class=\"w-full rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:opacity-90\">Send OTP</button></form><form id=\"otpStep\" class=\"mt-4 hidden space-y-3\"><div class=\"rounded-md border border-border bg-background p-2 text-xs text-muted-foreground\">Code sent to <span id=\"otpEmailLabel\" class=\"font-medium text-foreground\"></span>.</div><label class=\"block text-sm font-medium\" for=\"otpInput\">6-digit code</label> <input id=\"otpInput\" type=\"text\" inputmode=\"numeric\" pattern=\"[0-9]{6}\" maxlength=\"6\" required placeholder=\"123456\" class=\"w-full rounded-md border border-input bg-background px-3 py-2 text-sm tracking-[0.25em]\"><div class=\"grid grid-cols-2 gap-2\"><button id=\"otpBack\" type=\"button\" class=\"rounded-md border border-border bg-card px-3 py-2 text-sm hover:bg-accent\">Back</button> <button id=\"otpSubmit\" type=\"submit\" class=\"rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:opacity-90\">Verify</button></div></form><div id=\"loginStatus\" class=\"mt-4 min-h-[20px] text-sm text-muted-foreground\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
