// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside id=\"sidebar\" class=\"h-full border-r border-border bg-card/40 backdrop-blur\"><div class=\"p-3 border-b border-border flex items-center justify-between\"><div class=\"text-sm font-semibold\">Workspace</div><button id=\"sidebarProfile\" class=\"rounded-md border border-border bg-card px-2 py-1 text-xs hover:bg-accent\" type=\"button\">Me</button></div><div class=\"p-3 text-xs font-semibold text-muted-foreground\">Card Catalog</div><div class=\"space-y-2 px-3 pb-3\"><button data-spawn=\"coin\" class=\"w-full rounded-md border border-border bg-card px-3 py-2 text-left text-sm hover:bg-accent\">Coin</button> <button data-spawn=\"wood\" class=\"w-full rounded-md border border-border bg-card px-3 py-2 text-left text-sm hover:bg-accent\">Wood</button> <button data-spawn=\"berry\" class=\"w-full rounded-md border border-border bg-card px-3 py-2 text-left text-sm hover:bg-accent\">Berry</button> <button data-spawn=\"villager\" class=\"w-full rounded-md border border-border bg-card px-3 py-2 text-left text-sm hover:bg-accent\">Villager</button></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
