// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside id=\"sidebar\" class=\"\n\t\t\tfixed inset-y-0 left-0 z-50 w-[260px]\n\t\t\t-translate-x-full transition-transform duration-200\n\t\t\tborder-r border-border bg-card/95 backdrop-blur\n\t\t\tmd:static md:translate-x-0 md:bg-card/40\n\t\t\"><div class=\"p-3 border-b border-border flex items-center justify-between\"><div class=\"text-sm font-semibold\">Workspace</div><button id=\"sidebarProfile\" class=\"rounded-md border border-border bg-card px-2 py-1 text-xs hover:bg-accent\" type=\"button\">Me</button></div><div class=\"p-3 text-xs font-semibold text-muted-foreground\">Card Catalog</div><div class=\"space-y-2 px-3 pb-3\"><button data-spawn=\"event.create_user_submission\" type=\"button\">Create User Submission</button> <button data-spawn=\"agent.ai_tools\" type=\"button\">AI Agent</button> <button data-spawn=\"rule.is_manager\" type=\"button\">Is Manager?</button> <button data-spawn=\"integration.slack\" type=\"button\">Slack</button> <button data-spawn=\"integration.entra\" type=\"button\">Entra ID</button> <button data-spawn=\"integration.jira\" type=\"button\">Jira</button> <button data-spawn=\"action.invite_slack_channel\" type=\"button\">Invite to Channel</button> <button data-spawn=\"action.update_slack_profile\" type=\"button\">Update Profile</button> <button data-spawn=\"memory.state_db\" type=\"button\">State DB</button></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
